version: "3.7"

services:
  nja_server:
    build: ./nso-core
    image: kakavip198kaka/nja_server:0.1
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 60s
        max_failure_ratio: 0.3
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=12345678
      - DB_PORT=3306
      - DB_DATABASE=nja
      - REDIS_CACHE_DEFAULT=redis://redis:6379/1
      - TOPUP_CARD_API=https://api.doicard68.com/api/card-auto
      - TOPUP_CARD_API_KEY=C806331F-CC2A-4EAF-9148-B755DE567333
      - NSO_MS_API=http://nso-ms.tk/api/topup_card
    volumes:
      - ./nso-core/res:/app/res
      - ./nso-core/black_list_ips.txt:/app/log/black_list_ips.txt
    ports:
      - 14444:14444
    depends_on:
      - mysql
  nginx:
    restart: always
    image: kakavip198kaka/nginx:0.1
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nso-core/res:/home/app/res
    ports:
      - 80:80
    depends_on:
      - nja_admin
      - php_myadmin

  redis:
    image: redis:4.0.11
    environment:
      - "affinity:image==redis"
    volumes:
      - local_redis_data:/data

  nja_admin:
    restart: always
    build: ./nso-admin
    image: kakavip198kaka/nja_admin:0.1
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 60s
        max_failure_ratio: 0.3
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=12345678
      - DB_PORT=3306
      - DB_DATABASE=nja
    depends_on:
      - mysql
      - redis
    volumes:
      - static_volume:/code/static

  mysql:
    restart: always
    image: mysql:5.7.20
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=1073741824
    volumes:
      - local_mysql_data:/var/lib/mysql
      - ./mysql/backups:/backups
      - ./mysql/restores:/restores
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: root
      MYSQL_DATABASE: nja

  php_myadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123789
    ports:
      - 18085:80
    depends_on:
      - mysql

networks:
  default:
    driver: overlay
    attachable: true
volumes:
  local_mysql_data: null
  static_volume: null
  local_redis_data: null
